name: Kripto Bot Taymeri
on:
  schedule:
    # 1. Bakı vaxtı ilə səhər 10:00 (UTC 06:00)
    - cron: '0 6 * * *'
    # 2. Bakı vaxtı ilə axşam 18:00 (UTC 14:00)
    - cron: '0 14 * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Kodu yoxla
        uses: actions/checkout@v3
      - name: Python-u quraşdır
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Kitabxanaları yüklə
        run: pip install requests pandas ta
      - name: Botu işə sal
        run: python bot.py
